# Metabolic control analysis

In biochemistry, Michaelis–Menten kinetics is one of the best-known models of enzyme kinetics. The model takes the form of an equation describing the rate of enzymatic reactions, by relating reaction rate v to [S], the concentration of a substrate S. Its formula is given by

 $$v = \frac{d [P]}{d t} = \frac{ V_\max {[S]}}{K_\mathrm{M} + [S]}.$$
 
Here, $V_\max$ represents the maximum rate achieved by the system, at maximum (saturating) substrate concentrations. The Michaelis constant $K_\mathrm{M}$ is the substrate concentration at which the reaction rate is half of $V_\max$. Biochemical reactions involving a single substrate are often assumed to follow Michaelis–Menten kinetics, without regard to the model's underlying assumptions.

Rewriting Michaelis' equation, we get

 $$ln(v) = ln(V_\max {[S]}) - ln(K_\mathrm{M} + [S]) = ln(V_\max) + ln({[S]}) - ln(K_\mathrm{M} + [S])$$
 
This implies that the elasticity coefficient of this reaction is

$$ \varepsilon^v_{[S]} = \frac{\partial \ln v}{\partial \ln S} = 1 - \frac{\partial ln(K_\mathrm{M} + [S])}{\partial \ln [S]} = 1 - \frac{\partial ln(K_\mathrm{M} + [S])}{\partial (K_\mathrm{M} + [S])} \frac{\partial (K_\mathrm{M} + [S])}{\partial \ln [S]} = 1 - \frac{1}{K_\mathrm{M} + [S]} \frac{\partial [S]}{\partial \ln [S]} = 1 - \frac{[S]}{K_\mathrm{M} + [S]} = \frac{K_\mathrm{M}}{K_\mathrm{M} + [S]}$$

The unscaled elasticities are often depicted in matrix form, called the elasticity matrix. Given a network with m molecular species and n reactions, then the elasticity matrix is defined as:


$$\mathbf{\varepsilon} =
\begin{bmatrix} 
  \dfrac{\partial v_1}{\partial S_1} & \cdots & \dfrac{\partial v_1}{\partial S_m} \\ \vdots & \ddots & \vdots \\ \dfrac{\partial v_n}{\partial S_1} & \cdots & \dfrac{\partial v_n}{\partial S_m}  
\end{bmatrix}. $$


In [4]:
%pylab inline
import numpy as np

Populating the interactive namespace from numpy and matplotlib


In [33]:
# Create elasticity matrix. 7 molecules and 7 reactions
# Not considering the propane, since it doesnt react to another element.
e = zeros((7, 7))

# Define 7 K_m constants
K_AtoB = 0.47
K_Hbd = 1
K_Crt = 1
K_Ter = 1
K_YciA = 1
K_CAR = 1
K_ADO = 1

# Define 8 molecule concentrations
# A = Acetoacetyl-CoA
# B = Acetyl-CoA
# C = NADPH
# D = 3-hydroxybutyryl-CoA
# E = Crotonyl-CoA
# F = Butyryl-CoA
# G = Butyric-acid
# H = Butyraldehyde

A = 100
B = 10
C = 10
D = 10
E = 10
F = 10
G = 10
H = 10

# Write elasticity in the matrix
e[0,0] = K_AtoB/(K_AtoB+A)
e[1,1] = K_Hbd/(K_Hbd+B)
e[2,2] = K_Crt/(K_Crt+C)
e[3,3] = K_Ter/(K_Ter+D)
e[4,4] = K_YciA/(K_YciA+E)
e[5,5] = K_CAR/(K_CAR+F)
e[6,6] = K_ADO/(K_ADO+G)




e

array([[ 0.00467801,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ],
       [ 0.        ,  0.09090909,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.09090909,  0.        ,  0.        ,
         0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.09090909,  0.        ,
         0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.09090909,
         0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.09090909,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.09090909]])

In [20]:
print(b[0,1])

0


In [52]:
g = np.matrix([[1, 0, 0, 0, 0, 0], [1, 0, 0, 0, 0, 0], [1, 0, 0.25, -0.25, 0.25, -0.25], [1, 0, -0.25, 0.25, -0.25, 0.25], [1, 0, 0.25, -0.25, 0.25, -0.25], [1, 0, -0.25, 0.25, -0.25, 0.25]])
f = np.matrix([[0, 0, 0, 0], [1, 0, 0, 0], [0, 2, -1, 0], [0, 2, 0, -1], [0, 0, 1, 0], [0, 0, 0, 1]])
m = g*f
print(m.shape)
print(m)

(6, 4)
[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]
